name: Build binary releases
on:
  push:
    branches:
      - "master"
      - "sciter"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Setup Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'

      - name: "Setup Environment"
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
          export GO111MODULE=on
          sudo apt install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev nodejs gcc-mingw-w64
        shell: bash

      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build & test"
        run: |
          CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -ldflags "-extldflags -static" -H=windowsgui -o build/win_text.exe main.go

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            build/*
